|  8 |                                 | X    |               |           |    1044.003716 |       00:17:40 |
|  9 | PCA-250_PCA-300_view1.mat       |      |       0.69100 |       125 |       1.085379 |       00:06:06 |
| 10 | LLE-250_PCA-300_view1.mat       |      |       0.49500 |         1 |     199.411542 |       00:09:42 |
| 11 | Laplacian-250_PCA-300_view1.mat |      |       0.50100 |        37 |     138.775787 |                |
| 12 | Isomap-250_PCA-300_view1.mat    |      |       0.60700 |       103 |     401.509205 |       00:13:19 |
| 13 | LDA_view1.mat                   |      |        0.5460 |         1 |    6792.695376 |       01:53:22 |
| 14 | LDA_s_view1.mat                 |      |       0.50300 |         1 |    1604.669209 |                |
| 15 | LDA_PCA-300_view1.mat           |      |       0.56800 |         1 |       1.153220 |       00:00:07 |

*** errors
**** PCA
     no error
**** LLE
***** view1
Matrix is singular or close to singular for reduction and out-of-sample

{^HWarning: Matrix is singular to working precision.}^H
{^H> In lle at 83
  In compute_mapping at 202
  In dimension_reduction at 11
  In sge_experiment at 21}^H

{^HWarning: Matrix is singular to working precision.}^H
{^H> In out_of_sample at 111
  In dimension_reduction at 28
  In sge_experiment at 21}^H
***** s_view1

File Edit Options Buffers Tools Help                                                                                                                                      
{^HError using eigs/checkInputs (line 571)
Number of eigenvalues requested, k, must be a positive integer <= n.

Error in eigs (line 94)
[A,Amatrix,isrealprob,issymA,n,B,classAB,k,eigs_sigma,whch, ...

Error in lle (line 117)
        [mappedX, eigenvals] = eigs(M + eps * eye(n), no_dims + 1, tol,
        options);          % only need bottom (no_dims + 1) eigenvectors

Error in compute_mapping (line 202)
                        if isempty(varargin), [mappedA, mapping] = lle(A,
                        no_dims, 12, eig_impl);

Error in dimension_reduction (line 11)
  [DataM, mapping] = compute_mapping (Data, technique, dimension);

Error in sge_experiment (line 35)
      dimension_reduction (file{2}, reduction{2}, dimension{1});
}^H
^G
***** PCA-300

Matrix is singular or close to singular for reduction and out-of-sample

**** Laplacian
***** view1
{^HWarning: Colon operands must be real scalars.}^H
{^H> In verification_ml_test>PLDA_Learning_Threshold at 48
  In verification_ml_test at 26
  In accuracy at 15
  In sge_experiment at 25}^H
{^HWarning: Colon operands must be real scalars.}^H
{^H> In verification_ml_test>Verification_Test_Given_Likelihood at 86
  In verification_ml_test at 27
  In accuracy at 15
  In sge_experiment at 25}^H

***** s_view1
^HError using eigs/checkInputs (line 571)
Number of eigenvalues requested, k, must be a positive integer <= n.

Error in eigs (line 94)
[A,Amatrix,isrealprob,issymA,n,B,classAB,k,eigs_sigma,whch, ...

Error in laplacian_eigen (line 90)
        [mappedX, lambda] = eigs(L, D, no_dims + 1, tol, options);
        % only need bottom (no_dims + 1) eigenvectors

Error in compute_mapping (line 189)
            if isempty(varargin), [mappedA, mapping] = laplacian_eigen(A,
            no_dims, 12, 1, eig_impl);

Error in dimension_reduction (line 11)
  [DataM, mapping] = compute_mapping (Data, technique, dimension);

Error in sge_experiment (line 38)
      dimension_reduction (file{2}, reduction{3}, dimension{1});
}^H
^G

***** PCA-300
similar view1





**** Isomap
***** view1
^HWarning: Matrix is close to singular or badly scaled. Results may be
inaccurate. RCOND =  2.796467e-35.}^H
{^H> In out_of_sample at 58
  In dimension_reduction at 13
  In sge_experiment at 27}^H

***** s_view1
^HSubscripted assignment dimension mismatch.

Error in dimension_reduction (line 27)
    DataP(mapping.conn_comp, :) = DataM;

Error in sge_experiment (line 41)
      dimension_reduction (file{2}, reduction{4}, dimension{1});
}^H
^G

***** PCA-300
no problem

**** LDA
no problem
*** solutions
    Data is a redundant matrix as might be DataTT1 and DataTT2,
    therefore singular matrices appears as the covariance matrix of
    neighbouring points is computed.

    The solution is to construct a non redundant Data matrix, and use
    indices to symbolise similarity and dissimilarity
    pairs. extract_view1 and extract_view2 have to be rewritten.
* <2012-08-08 Wed>
** Tasks
*** Experiment with LDA
    - Test different dimensionality for LDA
    - Test a pre-reduction with PCA
*** Play with k
    - Test the accuracy obtained for different values of k
    - Implement an adaptative algorithm for neighbourhood finder
    - experiment with find_nn_adaptative
*** PCA reduction
    - PCA pre-reduction for non-linear methods
*** find explanation for results of LDA, Non-linear method
*** Test algorithms on swiss-roll dataset
*** Solve dimension error
    - Find right LLE dimension reduction
    - Study automatic dimension selection from Isomap
*** DONE Eigenproblem and dimension reduction for nonlinear methods
    CLOSED: [2012-08-10 Fri 20:22]
    - can the dimension be further reduced by simply removing additional features?
    - PCA Isomap LDA and LLE can be further reduced that way
    - Laplacian_eigen seems to be non stable
*** DONE convert extract_view2
    CLOSED: [2012-08-10 Fri 18:55]
*** DONE similar "unique" modification for testing dataset
    CLOSED: [2012-08-10 Fri 18:55]
    - in order to reduce redundancy, increase time and memory performances
    - make sure that the rest of the code is not impacted
    - find a new nomenclature for the variables
      train_Data test_Data train_DD train_SS test_DD test_SS
*** understand why Laplacian_eigen is unstable
    - and whether the result of the reduction is affected
** Experiments
*** Dataset intrinsic dimensionality
    
    | method    |  CorrDim | NearNbDim | PackingNumbers |     GMST | EigValue |      MLE |
    | dimension |   4.3531 |    0.0244 |                |  19.7681 |        3 |  47.4317 |
    | time      | 285.4606 |  145.2794 |                | 215.8538 |  82.1499 | 140.8669 |

*** Influence of k

| method     | Isomap |  LLE | Laplacian |
| acccuracy  |   0.65 | 0.66 |           |
| k          |     53 |  137 |           |
| dimension  |     84 |   12 |           |
|------------+--------+------+-----------|
| adaptative |        |      |           |

    - if the adaptative method is successful, precompute the
      neighbourhood graph for each of the views or pre-reduced views
      and modify the code accordingly

*** Dimensionality parameter

    given the best k-value, trace an accuracy/dimension graph for PCA,
    LDA, Isomap, LLE, Laplacian for no_dims=1:2000?
    - trace first for PCA to find the appropriate interval

*** PCA pre-reduction

    - influence of PCA pre-reduction on k, is it modified?
    - best PCA dimension to reducte to? same for every techniques?
    - relation between best PCA dimension accuracy and best PCA
      dimension pre-reduction      
    - x

	| method        |  LDA | Isomap | LLE | Laplacian |
	| accuracy      | 0.72 |        |     |           |
	| dimension     |   47 |        |     |           |
	| PCA-reduction | 88   |        |     |           |
